/*
 * 区块链服务API
 * 区块链服务
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package models;

import java.util.Objects;

import models.api.Jsonable;
import play.data.validation.Required;

import java.sql.Timestamp;

/**
 * Module
 */
public class Module  implements Jsonable {
  @Required
  private String moduleId = null;

  @Required
  private String moduleSpec = null;

  @Required
  private String manufacturer = null;

  @Required
  private Timestamp timestamp = null;

  public Module moduleId(String moduleId) {
    this.moduleId = moduleId;
    return this;
  }

   /**
   * 电池模组id
   * @return moduleId
  **/

  public String getModuleId() {
    return moduleId;
  }

  public void setModuleId(String moduleId) {
    this.moduleId = moduleId;
  }

  public Module moduleSpec(String moduleSpec) {
    this.moduleSpec = moduleSpec;
    return this;
  }

   /**
   * 电池模组规格
   * @return moduleSpec
  **/

  public String getModuleSpec() {
    return moduleSpec;
  }

  public void setModuleSpec(String moduleSpec) {
    this.moduleSpec = moduleSpec;
  }

  public Module manufacturer(String manufacturer) {
    this.manufacturer = manufacturer;
    return this;
  }

   /**
   * 生产厂家
   * @return manufacturer
  **/

  public String getManufacturer() {
    return manufacturer;
  }

  public void setManufacturer(String manufacturer) {
    this.manufacturer = manufacturer;
  }

  public Module timestamp(Timestamp timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Get timestamp
   * @return timestamp
  **/

  public Timestamp getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(Timestamp timestamp) {
    this.timestamp = timestamp;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Module module = (Module) o;
    return Objects.equals(this.moduleId, module.moduleId) &&
        Objects.equals(this.moduleSpec, module.moduleSpec) &&
        Objects.equals(this.manufacturer, module.manufacturer) &&
        Objects.equals(this.timestamp, module.timestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(moduleId, moduleSpec, manufacturer, timestamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Module {\n");
    
    sb.append("    moduleId: ").append(toIndentedString(moduleId)).append("\n");
    sb.append("    moduleSpec: ").append(toIndentedString(moduleSpec)).append("\n");
    sb.append("    manufacturer: ").append(toIndentedString(manufacturer)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

